### ISSUE TITLE
Time tracker

### ISSUE THREAD

**Issue by amREDOX** [Skchouhan753/far-bird-7999#4]
- [x] - Time tracker boilerplate
- [x] - Time tracker api
- [x] - Time tracker time set
- [x] - styling
